### ISSUE TITLE
Bug in remove_duplicates function - strange "pokemons"

### ISSUE THREAD

**Issue by CyberPotat42** [CyberPotat42/SUAI-Labs#17]
https://github.com/DenCoder618/SUAI-Labs/blob/55ffa5a86e2616c005ae8849003b7b6a486a25af/Semester_1/Lab_6/snippets.c#L316-L318

When removing duplicates on medium file, come words is corrupted (35 & 42):
```
34 -- libero
35 -- ╚"q
36 -- luctus
/ -------- /
41 -- mi
42 -- `)q
43 -- mollis
```

Idk what is this 👀

**Comment by DenCoder618** [comment]
i still don't know what caused the bug, but I have already passed all the labs 🤣

**Comment by CyberPotat42** [comment]
it's time to sleep 💤
